### ISSUE TITLE
Is it possible to use ollama models?`

### ISSUE THREAD

**Issue by ShravanSunder** [cztomsik/ava#19]
I am wondering if its possible to use ollama models already on my system?  that way we don't have to download models multiple times.

thanks!

**Comment by cztomsik** [comment]
Not at the moment, and it's not currently planned. It would be certainly nice, but the primary format is GGUF. When [this ticket](https://github.com/cztomsik/ava/issues/5) gets implemented, you might be able to use ollama as inference engine (with some features missing because ollama does not support everything we can do with raw model)

**Comment by cztomsik** [comment]
Can you clarify a little bit about how ollama works? Looking [at this](https://github.com/ollama/ollama/blob/main/docs/import.md), it seems like Modelfile is actually still referencing .gguf file so you should be able to just import that .gguf file in the Models->Installed screen
